In [1]:
# x_data = (예습시간, 복습시간)
# t_data = 1 (Pass), 0 (Fail)

import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

x_data.ndim =  2 , x_data.shape =  (9, 2)
t_data.ndim =  2 , t_data.shape =  (9, 1)


In [2]:
W = np.random.rand(2, 1)  # 2X1 행렬
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.21212013]
 [0.21761286]] , W.shape =  (2, 1) , b =  [0.063864] , b.shape =  (1,)


In [3]:
# classification 이므로 출력함수로 sigmoid 정의

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [4]:
# 최종출력은 y = sigmoid(Wx+b) 이며, 손실함수는 cross-entropy 로 나타냄

def loss_func(x, t):
    
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )

In [5]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [6]:
def error_val(x, t):
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

In [7]:
def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1  # True
    else:
        result = 0  # False
    
    return y, result

In [8]:
learning_rate = 1e-4  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(200001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  10.601252718591157 Initial W =  [[0.21212013]
 [0.21761286]] 
 , b =  [0.063864]
step =  0 error value =  5.632548111991719 W =  [[ 0.03321411]
 [-0.02008948]] , b =  [0.06339599]
step =  400 error value =  2.1648937070804615 W =  [[ 0.43450636]
 [-0.07830265]] , b =  [-2.83695086]
step =  800 error value =  1.5480912452846525 W =  [[ 0.54648363]
 [-0.02191536]] , b =  [-4.39706379]
step =  1200 error value =  1.25652250471917 W =  [[0.63144128]
 [0.01200828]] , b =  [-5.47341408]
step =  1600 error value =  1.0831826676891094 W =  [[0.70040015]
 [0.03652101]] , b =  [-6.30410919]
step =  2000 error value =  0.9660695729120945 W =  [[0.75872739]
 [0.05621488]] , b =  [-6.9870967]
step =  2400 error value =  0.8802529171060528 W =  [[0.80942035]
 [0.07316765]] , b =  [-7.57177939]
step =  2800 error value =  0.8137677693310714 W =  [[0.85432591]
 [0.08846665]] , b =  [-8.08640356]
step =  3200 error value =  0.7601432442164431 W =  [[0.89466675]
 [0.10273593]] , b

In [9]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data)

(array([0.12871902]), 0)

In [10]:
test_data = np.array([5, 8]) # (예습, 복습) = (5, 8) => Fail (0)

predict(test_data)

(array([0.0009898]), 0)

In [11]:
test_data = np.array([7, 21]) # (예습, 복습) = (7, 21) => Pass (1)

predict(test_data)

(array([0.99998956]), 1)

In [12]:
test_data = np.array([12, 0])  # (예습, 복습) = (12, 0) => Pass (1)

predict(test_data)

(array([0.6349398]), 1)

In [ ]:
for i in range(5):
    (a,b)=predict(test_x_data[i])
    print(a,b, test-y_data[i])