In [1]:
import numpy as np

# 수치미분 함수

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

# sigmoid 함수

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [2]:
class LogicGate:
        
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4,2)  # 4개의 입력데이터 x1, x2 에 대하여 batch 처리 행렬
        self.__tdata = tdata.reshape(4,1)  # 4개의 입력데이터 x1, x2 에 대한 각각의 계산 값 행렬
        
        # 2층 hidden layer unit : 6개 가정,  가중치 W2, 바이어스 b2 초기화
        self.__W2 = np.random.rand(2,6)  # weight, 2 X 6 matrix
        self.__b2 = np.random.rand(6)
        
        # 3층 output layer unit : 1 개 , 가중치 W3, 바이어스 b3 초기화
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
                        
        # 학습률 learning rate 초기화
        self.__learning_rate = 1e-2
    
        print(self.name + " object is created")
            
    def feed_forward(self):        # feed forward 를 통하여 손실함수(cross-entropy) 값 계산
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )    
    
    def loss_val(self):          # 외부 출력을 위한 손실함수(cross-entropy) 값 계산 
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )
    
    
    # 수치미분을 이용하여 손실함수가 최소가 될때 까지 학습하는 함수
    def train(self):
        
        f = lambda x : self.feed_forward()
        print("Initial loss value = ", self.loss_val())
        
        for step in  range(10001):
            
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
        
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
    
            if (step % 400 == 0):
                print("step = ", step, "  , loss value = ", self.loss_val())
                
    
    # query, 즉 미래 값 예측 함수
    def predict(self, xdata):
        
        z2 = np.dot(xdata, self.__W2) + self.__b2         # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
    
        return y, result

In [3]:
# AND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)

and_obj.train()

AND object is created
Initial loss value =  5.921010474398426
step =  0   , loss value =  5.693210993432966
step =  400   , loss value =  2.2219234496256233
step =  800   , loss value =  2.079613053306578
step =  1200   , loss value =  1.8522139765387273
step =  1600   , loss value =  1.5273833334962839
step =  2000   , loss value =  1.1784490800675869
step =  2400   , loss value =  0.8636756754763776
step =  2800   , loss value =  0.6221434293171311
step =  3200   , loss value =  0.4582070034268961
step =  3600   , loss value =  0.34899437069181816
step =  4000   , loss value =  0.27440817862809064
step =  4400   , loss value =  0.22183519152514541
step =  4800   , loss value =  0.18362485743353374
step =  5200   , loss value =  0.15506137535805858
step =  5600   , loss value =  0.13316524745395872
step =  6000   , loss value =  0.11600303695903126
step =  6400   , loss value =  0.10228620719258363
step =  6800   , loss value =  0.09113380478447103
step =  7200   , loss value =  0.081

In [4]:
# AND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00012461]), 0)
(array([0.01131003]), 0)
(array([0.01204031]), 0)
(array([0.97762507]), 1)


In [5]:
# OR Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)
or_obj.train()

OR object is created
Initial loss value =  2.418214961384951
step =  0   , loss value =  2.4056912412875473
step =  400   , loss value =  1.8874394689027536
step =  800   , loss value =  1.6614624353899785
step =  1200   , loss value =  1.3680755917846004
step =  1600   , loss value =  1.0527328554023367
step =  2000   , loss value =  0.7806819403616935
step =  2400   , loss value =  0.5779132968934511
step =  2800   , loss value =  0.43621169830637696
step =  3200   , loss value =  0.33843438348094135
step =  3600   , loss value =  0.27003884421864605
step =  4000   , loss value =  0.2210119700430123
step =  4400   , loss value =  0.18490170733329903
step =  4800   , loss value =  0.15759901859757877
step =  5200   , loss value =  0.13645687002056162
step =  5600   , loss value =  0.11973409724282938
step =  6000   , loss value =  0.10625766091503291
step =  6400   , loss value =  0.0952180110956689
step =  6800   , loss value =  0.0860434866734163
step =  7200   , loss value =  0.078

In [6]:
# OR Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(or_obj.predict(data))

(array([0.02876943]), 0)
(array([0.99130571]), 1)
(array([0.99162507]), 1)
(array([0.99951754]), 1)


In [7]:
# NAND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)

nand_obj.train()

NAND object is created
Initial loss value =  3.5999840376869443
step =  0   , loss value =  3.558856513666544
step =  400   , loss value =  2.2216599900811427
step =  800   , loss value =  2.1183081065581755
step =  1200   , loss value =  1.9697412146403281
step =  1600   , loss value =  1.746687706498132
step =  2000   , loss value =  1.4406309515300364
step =  2400   , loss value =  1.0952174579953735
step =  2800   , loss value =  0.7978592069071533
step =  3200   , loss value =  0.5794535480497565
step =  3600   , loss value =  0.42804744851279464
step =  4000   , loss value =  0.3254541858593366
step =  4400   , loss value =  0.25535319037215054
step =  4800   , loss value =  0.20616476255974686
step =  5200   , loss value =  0.17055359837553952
step =  5600   , loss value =  0.14399233928781782
step =  6000   , loss value =  0.12364915137382576
step =  6400   , loss value =  0.10770498501526155
step =  6800   , loss value =  0.09495663490715901
step =  7200   , loss value =  0.08

In [8]:
# NAND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99991549]), 1)
(array([0.98809955]), 1)
(array([0.98807792]), 1)
(array([0.02149715]), 0)


In [9]:
# XOR Gate 객체 생성

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])


xor_obj = LogicGate("XOR", xdata, tdata)

xor_obj.train()

XOR object is created
Initial loss value =  6.32355372035828
step =  0   , loss value =  6.185265163176068
step =  400   , loss value =  2.787818035686669
step =  800   , loss value =  2.783158458710851
step =  1200   , loss value =  2.779860013550906
step =  1600   , loss value =  2.7774358605225893
step =  2000   , loss value =  2.7755734071267617
step =  2400   , loss value =  2.774062183898021
step =  2800   , loss value =  2.7727518333370638
step =  3200   , loss value =  2.77152615475556
step =  3600   , loss value =  2.770285664456172
step =  4000   , loss value =  2.76893424913332
step =  4400   , loss value =  2.767366930365447
step =  4800   , loss value =  2.7654562540775665
step =  5200   , loss value =  2.763034690249688
step =  5600   , loss value =  2.7598698338017136
step =  6000   , loss value =  2.755628312090218
step =  6400   , loss value =  2.749823493009632
step =  6800   , loss value =  2.7417419807518035
step =  7200   , loss value =  2.730344978884487
step =  7

In [10]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.32211323]), 0)
(array([0.65346168]), 1)
(array([0.47412306]), 0)
(array([0.55370727]), 1)
